<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DwApcInfo\Module'                    => __DIR__ . '/Module.php',
    'DwApcInfo\Controller\InfoController' => __DIR__ . '/src/DwApcInfo/Controller/InfoController.php',
);
