<h3>APC-Info goes here...</h3>
<p><?php echo $this->info_msg; ?></p>

<div class="row">
  <div class="col-xs-12 col-md-8 col-lg-6">
    <h4>Allgemeine Cache Informationen</h4>
    <table class="table table-striped table-bordered">
      <tbody>
        <tr><td>APC Version</td><td><?php echo $general_info['apc_version']; ?></td></tr>
        <tr><td>PHP Version</td><td><?php echo $general_info['php_version']; ?></td></tr>
        <tr><td>APC Host</td><td><?php echo $general_info['apc_host']; ?></td></tr>
        <tr><td>Server Software</td><td><?php echo $general_info['server_software']; ?></td></tr>
        <tr>
          <td>Shared Memory</td>
          <td>
            <?php echo $general_info['num_shm_seg']; ?> Segment(e) mit <?php echo $general_info['shm_seg_size']; ?> <br>
            (<?php echo $general_info['memory_type']; ?> Memory, <?php echo $general_info['locking_type']; ?> Locking)
          </td>
        </tr>
        <tr><td>Startzeit</td><td><?php echo $general_info['start_time']; ?></td></tr>
        <tr><td>Up-Time</td><td><?php echo $general_info['uptime']; ?></td></tr>
        <tr><td>Datei Upload Support</td><td><?php echo $general_info['file_upload_support']; ?></td></tr>
      </tbody>
    </table>
  </div>
</div>

<?php var_dump($general_info); ?>